### ISSUE TITLE
Can't add dependency with yarn@2

### ISSUE THREAD

**Issue by urimaro** [honkit/honkit#104]
I tried to create a new project with yarn.
But `yarn add` causes an error.

### Steps to reproduce

1. Make a directory and move into it.
2. Run following commands.
3. Specify Node version
    ```
    echo v14.6.0 > .node-version
    ````
4. Install yarn per-project
    ```
    yarn policies set-version berry
    yarn set version berry
    ```
5. Create a new package.
    ```
    yarn inti
    ```
6. Add dependency.
    ```
    yarn add --dev honkit
    ```

### Expected behavior

The dependency of HonKit is added normally.

### Actual behavior

An Error occurred.
HonKit was not added to `package.json`.
<details><summary>Output of <code>yarn add --dev honkit</code></summary>

```
> yarn add --dev honkit                                                                                                                                                                                             (master)
➤ YN0000: ┌ Resolution step
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0032: │ fsevents@npm:2.1.3: Implicit dependencies on node-gyp are discouraged
➤ YN0001: │ Error: cheerio@^0.20.0 && >=0.20.0 isn't supported by any available resolver
    at i.getResolverByDescriptor (/Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:266590)
    at i.bindDescriptor (/Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:266044)
    at /Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:288133
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 2)
    at async ne.resolveEverything (/Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:287456)
    at async /Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:304371
    at async f.startTimerPromise (/Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:313773)
    at async ne.install (/Users/goh/sandbox/sample/.yarn/releases/yarn-2.1.1.cjs:2:304005)
➤ YN0000: └ Completed in 11.4s
➤ YN0000: Failed with errors in 11.4s
```
</details>

### System configuration

- **Node.js version**: v14.6.0
- **npm version**: 6.14.6
- **Yarn version**: 2.1.1

**Comment by azu** [comment]
> Error: cheerio@^0.20.0 && >=0.20.0 isn't supported by any available resolver

It looks like that yarn@2 does not support this version syntax.
https://github.com/honkit/honkit/blob/91213fbba9adadac0ba7a820b8bb6df38bb325af/packages/%40honkit/html/package.json#L41

```diff
-  "cheerio": "^0.20.0 && >=0.20.0",
+ "cheerio": "^0.20.0",
```

Does this diff fix this?

I do not know whether or not `^0.20.0 && >=0.20.0` is valid syntax of semver.

**Comment by azu** [comment]
> ```diff
> - "cheerio": "^0.20.0 && >=0.20.0",
> + "cheerio": "^0.20.0",
> ```

I've released [v3.5.5](https://github.com/honkit/honkit/releases/tag/v3.5.5) that includes the above diff.

**Comment by urimaro** [comment]
Thank you for your quick response!
It works!

<details><summary>Output of <code>yarn add --dev honkit</code></summary>
```
> yarn add --dev honkit
➤ YN0000: ┌ Resolution step
➤ YN0061: │ request@npm:2.88.2 is deprecated: request has been deprecated, see https://github.com/request/request/issues/3142
➤ YN0061: │ har-validator@npm:5.1.5 is deprecated: this library is no longer supported
➤ YN0032: │ fsevents@npm:2.1.3: Implicit dependencies on node-gyp are discouraged
➤ YN0032: │ fsevents@npm:2.1.3: Implicit dependencies on node-gyp are discouraged
➤ YN0000: └ Completed in 31.51s
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:18.1.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs@npm:15.3.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ statuses@npm:1.5.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tough-cookie@npm:2.5.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 15.16s
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0.43s
➤ YN0000: Done with warnings in 47.18s
```
</details>

**Comment by azu** [comment]
Thanks to confirm!

This issue is resolved
