### ISSUE TITLE
Can't execute `honkit serve` with yarn@2

### ISSUE THREAD

**Issue by urimaro** [honkit/honkit#131]
## Summary

When I execute `honkit serve` with yarn 2.2.2,
`yarn run honkit serve` causes an error.

- HonKit version: 3.6.6

## Step to reproduce

1. Set Node.js version: v14.12.0.
2. `yarn set version berry`.
3. `yarn init`.
4. `yarn add --dev honkit`
5. `yarn run honkit serve`

- [urimaro/honkit_sample](https://github.com/urimaro/honkit_sample)

## Expected results

Preview and serve README.md.

## Actual results

```
goh@goh ~/s/honkit_sample> yarn run honkit serve --log debug                                                                                                                                                                          (master)
Live reload server started on port: 35729
Press CTRL+C to quit ...

Starting server ...
debug: readme found at README.md 
warn: no summary file in this book 
debug: cleanup folder "/Users/goh/sandbox/honkit_sample/_book" 
ReferenceError: Failed to load HonKit's plugin module: "livereload" is not found.

cwd: /Users/goh/sandbox/honkit_sample
baseDir: 


    at PluginResolver.resolvePluginPackageName (/Users/goh/sandbox/honkit_sample/.yarn/cache/honkit-npm-3.6.6-ae72a47b44-9d5f6453a5.zip/node_modules/honkit/lib/plugins/PluginResolver.js:72:19)
    at /Users/goh/sandbox/honkit_sample/.yarn/cache/honkit-npm-3.6.6-ae72a47b44-9d5f6453a5.zip/node_modules/honkit/lib/plugins/loadForBook.js:27:34
    at /Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:3015:23)
    at seqIterate (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:604:16)
    at IndexedIterable.IndexedSeq.__iterate (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:320:14)
    at IndexedIterable.toArray (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:4258:23)
    at List [as constructor] (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:2065:62)
    at reify (/Users/goh/sandbox/honkit_sample/.yarn/cache/immutable-npm-3.8.2-8bba11f18f-08e65dd057.zip/node_modules/immutable/dist/immutable.js:3570:37)
```

**Comment by azu** [comment]
Probably, this is related to [Plug'n'Play | Yarn - Package Manager](https://yarnpkg.com/features/pnp)

HonKit is based on `require.resolve` logic. 
https://github.com/honkit/honkit/blob/master/packages/honkit/src/plugins/PluginResolver.ts
https://github.com/gbk/try-resolve/blob/master/index.js
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

I do not have knowledge about PnP support yet.

Related discussion #133

**Comment by urimaro** [comment]
Thank you for replying.
I don't mind if you close this issue to treat with #133.
