### ISSUE TITLE
typo? _layouts/website/page.html

### ISSUE THREAD

**Issue by dogatana** [honkit/honkit#136]
## Summary

I found following lines in page.html
```
    <script>
        var gitbook = gitbook || [];
        gitbook.push(function() {
            gitbook.page.hasChanged({{ template.getJSContext()|dump|safe }});
        });
    </script>
```

Is `{{ ... }}` correct?

https://github.com/honkit/honkit/blob/master/packages/%40honkit/theme-default/_layouts/website/page.html

- HonKit version: 3.6.6

## Step to reproduce

1. enter following code.
```
let b = "b";

let obj1 = { b };
let obj2 = {{ b }};

dump(obj1);
dump(obj2);

function dump(obj) {
    for (const k in obj) {
        console.log(`${k}: ${obj[k]}`);
    }
}
```
2. `node test.js` shows error.

```
C:\usr\sandbox\js
> node test.js
C:\usr\sandbox\js\test.js:4
let obj2 = {{ b }};
            ^

SyntaxError: Unexpected token '{'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by azu** [comment]
Probably, `{{...}}` is [Nunjucks](https://mozilla.github.io/nunjucks/templating.html) syntax.
Theme code will be compiled by [Nunjucks](https://mozilla.github.io/nunjucks/templating.html) before running.

**Comment by dogatana** [comment]
Thank you your quick answer.
I understood.
