### ISSUE TITLE
KaTeX plugin

### ISSUE THREAD

**Issue by fenuks** [honkit/honkit#217]
## Summary

I'm trying to build https://github.com/cs3110/textbook, and that book requires katex plugin. Searching for `katex` yields result to faq file where it is stated it is supported (along with mathjax plugin). How it can be installed? There seems to be no such plugin on npm.

- HonKit version: 3.6.20

## Step to reproduce

1. git clone https://github.com/cs3110/textbook && cd textbook
2. honkit epub . 3110.epub
3. See error.

- Link to code example:

https://github.com/cs3110/textbook

## Expected results
KaTeX plugin can be installed, and epub built.

## Actual result

$ honkit epub . 3110.epub --log=debug
```
debug: readme found at README.md 
debug: summary file found at SUMMARY.md 
debug: cleanup folder "/tmp/tmp-408929dX4b6qJ8P1Ue" 
(node:408929) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
ReferenceError: Failed to load HonKit's plugin module: "katex" is not found.

cwd: /tmp/textbook
baseDir: 


    at PluginResolver.resolvePluginPackageName (/tmp/textbook/node_modules/honkit/lib/plugins/PluginResolver.js:74:19)
    at /tmp/textbook/node_modules/honkit/lib/plugins/loadForBook.js:26:34
    at /tmp/textbook/node_modules/immutable/dist/immutable.js:3016:46
    at List.__iterate (/tmp/textbook/node_modules/immutable/dist/immutable.js:2206:13)
    at IndexedIterable.mappedSequence.__iterateUncached (/tmp/textbook/node_modules/immutable/dist/immutable.js:3015:23)
    at seqIterate (/tmp/textbook/node_modules/immutable/dist/immutable.js:604:16)
    at IndexedIterable.IndexedSeq.__iterate (/tmp/textbook/node_modules/immutable/dist/immutable.js:320:14)
    at IndexedIterable.toArray (/tmp/textbook/node_modules/immutable/dist/immutable.js:4258:23)
    at List [as constructor] (/tmp/textbook/node_modules/immutable/dist/immutable.js:2065:62)
    at reify (/tmp/textbook/node_modules/immutable/dist/immutable.js:3570:37)
```

**Comment by azu** [comment]
> ReferenceError: Failed to load HonKit's plugin module: "katex" is not found.

This error means that `gitbook-plugin-katex` or `honkit-plugin-katex` module is not found in `node_modules` dirs.

You need to install katex plugin with npm.

```
npm init --yes # create package.json
npm install gitbook-plugin-katex honkit --save-dev # install honkit and plugins
npx honkit build # build
```

HonKit does not bundle npm, so you need to install plugin manually.

**Comment by fenuks** [comment]
Thank you very much, I thought you forked plugin as well, didn't try to build it with old one from gitbook. It worked, thank you again.
