### ISSUE TITLE
honkit parse on a multilingual book failes

### ISSUE THREAD

**Issue by kakkun61** [honkit/honkit#270]
## Summary

`honkit parse` on a multilingual book fails.

- HonKit version: 3.7.3

## Step to reproduce

```
$ npm init
$ npm install --save-dev honkit
$ npx honkit init
$ echo '- [English](en)' > LANGS.md
$ mkdir en
$ touch en/README.md
$ npx honkit parse
```

## Expected results

No errors occur.

## Actual results

```
$ npx honkit parse --log debug
debug: languages index file found at LANGS.md
info: parsing multilingual book, with 1 languages
debug: readme found at README.md
warn: no summary file in this book
info: Book located in: C:\Users\kazuki\AppData\Local\Temp\honkit-parse
info: 2 languages
TypeError: lang.getTitle is not a function
    at C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\honkit\lib\cli\parse.js:38:42
    at C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:3016:36
    at ObjectSeq.__iterate (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:418:13)
    at mappedSequence.__iterateUncached (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:3015:23)
    at seqIterate (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:604:16)
    at Seq.__iterate (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:274:14)
    at Record.__iterate (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:3723:93)
    at Languages.forEach (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\immutable\dist\immutable.js:4381:19)
    at printMultingualBook (C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\honkit\lib\cli\parse.js:37:15)
    at C:\Users\kazuki\AppData\Local\Temp\honkit-parse\node_modules\honkit\lib\cli\parse.js:58:17
```

**Comment by azu** [comment]
> `honkit parse` on a multilingual book fails.

Does `honkit build` work in same book?

**Comment by azu** [comment]
I've fixed in https://github.com/honkit/honkit/releases/tag/v3.7.4
