### ISSUE TITLE
TypeError: parse is not a function

### ISSUE THREAD

**Issue by kristofer-lp8f** [honkit/honkit#298]
## Summary

Running honkit in a `yarn`'d monorepo causes `TypeError`

- HonKit version: `4.0.0.`

## Step to reproduce

1. `git clone https://github.com/island-is/island.is`
2. `yarn add --dev honkit`
3. `yarn honkit init --log=debug`

Any of `init`, `build`, `serve`, etc. will cause the same error.

## Expected results
Non-error

## Actual results

```
TypeError: parse is not a function
    at compileUnsafe (/var/home/user/honkit-reproduce/node_modules/cheerio/node_modules/css-select/lib/compile.js:31:14)
    at select (/var/home/user/honkit-reproduce/node_modules/cheerio/node_modules/css-select/index.js:18:49)
    at CSSselect (/var/home/user/honkit-reproduce/node_modules/cheerio/node_modules/css-select/index.js:41:9)
    at exports.find (/var/home/user/honkit-reproduce/node_modules/cheerio/lib/api/traversing.js:34:21)
    at module.exports (/var/home/user/honkit-reproduce/node_modules/cheerio/lib/cheerio.js:81:18)
    at new initialize (/var/home/user/honkit-reproduce/node_modules/cheerio/lib/static.js:26:20)
    at initialize (/var/home/user/honkit-reproduce/node_modules/cheerio/lib/static.js:23:14)
    at Object.parse (/var/home/user/honkit-reproduce/node_modules/@honkit/html/lib/dom.js:17:17)
    at parseSummary (/var/home/user/honkit-reproduce/node_modules/@honkit/html/lib/summary.js:140:19)
    at /var/home/user/honkit-reproduce/node_modules/@honkit/html/lib/index.js:26:19
```

**Comment by azu** [comment]
Thanks for report.

I don't know why, but it seems that cheerio is broken in your repository.

Run following script

```js
const cheerio = require('cheerio');
const $ = cheerio.load('<h2 class="title">Hello world</h2>');

$('h2.title').text('Hello there!');
$('h2').addClass('welcome');

$(".test")
console.log($.html());
```

and I get same error:

```
node index.js
/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/node_modules/css-select/lib/compile.js:31
	var token = parse(selector, options);
	            ^

TypeError: parse is not a function
    at compileUnsafe (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/node_modules/css-select/lib/compile.js:31:14)
    at select (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/node_modules/css-select/index.js:18:49)
    at CSSselect (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/node_modules/css-select/index.js:41:9)
    at initialize.exports.find (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/lib/api/traversing.js:34:21)
    at initialize.module.exports (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/lib/cheerio.js:81:18)
    at new initialize (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/lib/static.js:26:20)
    at initialize (/Users/azu/ghq/github.com/island-is/island.is/node_modules/cheerio/lib/static.js:23:14)
    at Object.<anonymous> (/Users/azu/ghq/github.com/island-is/island.is/index.js:4:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

Perhaps updating cheerio might fix it  #281

**Comment by kristofer-lp8f** [comment]
Testing updating...

**Comment by azu** [comment]
I remove https://github.com/island-is/island.is/blob/8476d6741c90742c531e5fe8654718f89d589d61/package.json#L454 and HonKit works.
This `resolusion` affect HonKit's dependencies.

This issue is `resolusion` setting issue.
https://yarnpkg.com/configuration/manifest/#resolutions
