### ISSUE TITLE
Mathjax plugin does not build

### ISSUE THREAD

**Issue by alexhkurz** [honkit/honkit#325]
## Summary

Mathjax plugin does not build

- HonKit version: 4.0.4

## Step to reproduce

```
npm install honkit --save-dev
npx honkit init
```

add book.json:

```
{
    "plugins": ["mathjax"]
}
```

run

```
npx honkit build
```
- Link to code example: https://github.com/alexhkurz/coalgebraic-logic-honkit

## Expected results

builds 

## Actual results

```
(base) ~/alexhkurz-at-github/coalgebraic-logic-honkit > npx honkit build  
info: 6 plugins are installed 
info: 6 explicitly listed 
info: plugin "highlight" is loaded
info: plugin "search" is loaded
info: plugin "lunr" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
Error [PluginError]: Error with plugin "mathjax": Unexpected token '<<'
    at createError (/Users/alexanderkurz/node_modules/error/typed.js:31:22)
    at new createError (/Users/alexanderkurz/node_modules/error/wrapped.js:88:19)
    at /Users/alexanderkurz/node_modules/honkit/lib/plugins/loadPlugin.js:67:23
    at _fulfilled (/Users/alexanderkurz/node_modules/q/q.js:854:54)
    at /Users/alexanderkurz/node_modules/q/q.js:883:30
    at Promise.promise.promiseDispatch (/Users/alexanderkurz/node_modules/q/q.js:816:13)
    at /Users/alexanderkurz/node_modules/q/q.js:877:14
    at runSingle (/Users/alexanderkurz/node_modules/q/q.js:137:13)
    at flush (/Users/alexanderkurz/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  type: 'plugin',
  plugin: 'mathjax',
  causeMessage: "Unexpected token '<<'",
  origMessage: "Unexpected token '<<'",
  fullType: 'plugin~!~error.wrapped-unknown'
}
```

**Comment by azu** [comment]
Thanks for report.

This is mathjax plugin issue, it is not honkit issue.
https://github.com/GitbookIO/plugin-mathjax/blob/master/index.js
mathjax plugin v2 is broken.

Probably, v1.x works?
https://github.com/GitbookIO/plugin-mathjax/blob/1.1.2/index.js

**Comment by alexhkurz** [comment]
Thanks ... do you know how I can tell honkit to use mathjax version 1 instead?

**Comment by azu** [comment]
```
npm install --save-dev gitbook-plugin-mathjax@1
```

**Comment by alexhkurz** [comment]
Thanks again ... after `npx honkit build` this leads to

```
...
Error [PluginError]: Error with plugin "mathjax": Cannot find module 'mathjax/unpacked/MathJax'
...
```

**Comment by azu** [comment]
I am unfamilar with mathjax plugin, but [This article](https://github-nakasho.github.io/pro/gitbook) suggest to install `mathjax` package too.

```
npm install mathjax@2.7.6 --save-dev
```

**Comment by alexhkurz** [comment]
Thank you so much, that seems to work.
