### ISSUE TITLE
error with export pdf 

### ISSUE THREAD

**Issue by ykla** [honkit/honkit#404]
## Summary

error with export pdf 

- HonKit version: 5.1.4

## Step to reproduce

1. npx honkit pdf ./ ./mybook.pdf

- Link to code example:

<details>
  <summary>code example</summary>
···
error: error while generating page "a/chou-xiang-dui-xiang-abstract-objects-jos-l.-falguera-concha-martnezvidal-and-gideon-rosen.md":
error: error while generating page "a/a-luo-bei-lun-arrows-theorem-michael-morreau.md":
error: error while generating page "b/xin-nian-de-xing-shi-hua-biao-shu-belief-formal-representations-of-konstantin-genin-and-franz-huber.md":
error: error while generating page "c/xuan-ze-gong-li-choice-axiom-of-john-l.-bell.md":
error: error while generating page "d/ding-yi-definitions-anil-gupta-and-stephen-mackereth.md":
error: error while generating page "g/bo-yi-lun-game-theory-don-ross/bo-yi-lun-de-ren-shi-lun-ji-chu-epistemic-foundations-of-eric-pacuit-and-olivier-roy.md":
error: error while generating page "g/na-er-xun-gu-de-man-goodman-nelson-daniel-cohnitz-and-marcus-rossberg/README.md":
Template render error: (C:\Users\ykla\Documents\1\a\chou-xiang-dui-xiang-abstract-objects-jos-l.-falguera-concha-martnezvidal-and-gideon-rosen.md)
  SyntaxError: Invalid or unexpected token
    at Object._prettifyError (C:\Users\ykla\node_modules\nunjucks\src\lib.js:32:11)
    at Template.render (C:\Users\ykla\node_modules\nunjucks\src\environment.js:442:21)
    at Environment.renderString (C:\Users\ykla\node_modules\nunjucks\src\environment.js:313:17)
    at Promise.apply (C:\Users\ykla\node_modules\q\q.js:1185:26)
    at Promise.promise.promiseDispatch (C:\Users\ykla\node_modules\q\q.js:808:41)
    at C:\Users\ykla\node_modules\q\q.js:1411:14
    at runSingle (C:\Users\ykla\node_modules\q\q.js:137:13)
    at flush (C:\Users\ykla\node_modules\q\q.js:125:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```
</details>

## Expected results

## Actual results

```
debug: calling hook "page"
error: error while generating page "a/chou-xiang-dui-xiang-abstract-objects-jos-l.-falguera-concha-martnezvidal-and-gideon-rosen.md":
error: error while generating page "a/a-luo-bei-lun-arrows-theorem-michael-morreau.md":
error: error while generating page "b/xin-nian-de-xing-shi-hua-biao-shu-belief-formal-representations-of-konstantin-genin-and-franz-huber.md":
error: error while generating page "c/xuan-ze-gong-li-choice-axiom-of-john-l.-bell.md":
error: error while generating page "d/ding-yi-definitions-anil-gupta-and-stephen-mackereth.md":
error: error while generating page "g/bo-yi-lun-game-theory-don-ross/bo-yi-lun-de-ren-shi-lun-ji-chu-epistemic-foundations-of-eric-pacuit-and-olivier-roy.md":
error: error while generating page "g/na-er-xun-gu-de-man-goodman-nelson-daniel-cohnitz-and-marcus-rossberg/README.md":
Template render error: (C:\Users\ykla\Documents\1\a\chou-xiang-dui-xiang-abstract-objects-jos-l.-falguera-concha-martnezvidal-and-gideon-rosen.md)
  SyntaxError: Invalid or unexpected token
    at Object._prettifyError (C:\Users\ykla\node_modules\nunjucks\src\lib.js:32:11)
    at Template.render (C:\Users\ykla\node_modules\nunjucks\src\environment.js:442:21)
    at Environment.renderString (C:\Users\ykla\node_modules\nunjucks\src\environment.js:313:17)
    at Promise.apply (C:\Users\ykla\node_modules\q\q.js:1185:26)
    at Promise.promise.promiseDispatch (C:\Users\ykla\node_modules\q\q.js:808:41)
    at C:\Users\ykla\node_modules\q\q.js:1411:14
    at runSingle (C:\Users\ykla\node_modules\q\q.js:137:13)
    at flush (C:\Users\ykla\node_modules\q\q.js:125:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```


My book in <https://github.com/taophilosophy/SEP-CN>

**Comment by davmillar** [comment]
I'm also having issues exporting as PDF. I tried installing the required module in the error message I received, but the error persists:

```
$ yarn honkit pdf ./ ./help.pdf
(node:1789264) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
info: 5 plugins are installed 
info: 5 explicitly listed 
info: plugin "highlight" is loaded
info: plugin "search" is loaded
info: plugin "lunr" is loaded
info: plugin "fontsettings" is loaded
info: plugin "theme-default" is loaded
info: found 4 pages 
info: found 5 asset files 
Error [InstallRequiredError]: "ebook-convert" is not installed.
Install it from Calibre: https://calibre-ebook.com
    at Object.createError [as RequireInstallError] (/home/millard/dev/[redacted]/node_modules/error/typed.js:31:22)
    at /home/millard/dev/[redacted]/node_modules/honkit/lib/output/ebook/onFinish.js:65:39
    at _rejected (/home/millard/dev/[redacted]/node_modules/q/q.js:864:24)
    at /home/millard/dev/[redacted]/node_modules/q/q.js:890:30
    at Promise.when (/home/millard/dev/[redacted]/node_modules/q/q.js:1142:31)
    at Promise.promise.promiseDispatch (/home/millard/dev/[redacted]/node_modules/q/q.js:808:41)
    at /home/millard/dev/[redacted]/node_modules/q/q.js:624:44
    at runSingle (/home/millard/dev/[redacted]/node_modules/q/q.js:137:13)
    at flush (/home/millard/dev/[redacted]/node_modules/q/q.js:125:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  type: 'install.required',
  cmd: 'ebook-convert',
  code: 'ENOENT',
  install: 'Install it from Calibre: https://calibre-ebook.com',
  fullType: 'install.required'
}
```

**Comment by davmillar** [comment]
@ykla your book repo link 404s -- are you able to repost it?

**Comment by ykla** [comment]
Sorry, too much time has passed, and the original project has been deleted. Initially, it was for exporting a project with a structure similar to Gitbook into a PDF. With someone's help, I have already placed a tool for exporting Gitbook projects on GitHub, and now I no longer have a similar need. You can refer to <https://github.com/FreeBSD-Ask/gitbook-pdf-export>. Thank you very much for your reply.
